### ISSUE TITLE
MongoError

### ISSUE THREAD

**Issue by yEs1do** [fython/PackageTracker-NodeServer#2]
输入：
> $ npm start

之后屏幕输出：
>  packagetracker-push@0.1.0 start /root/PackageTracker-NodeServer
>  node ./server.js
> Connecting to mongodb://127.0.0.1:27017/ptpush...
> (node:18132) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
> Disconnected.
> failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

**Comment by fython** [comment]
很抱歉，忘了在 README 上说明本服务需要额外安装 MongoDB 作为服务器，稍候我会添加说明，你可以先自行搜索安装方式解决。

**Comment by yEs1do** [comment]
@fython 好的，谢谢！

**Comment by fython** [comment]
已补充说明。感谢反馈。
